apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mongoexpress-deployment 
  labels:
    app: mongoExpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoExpress
  template:
    metadata:
      labels:
        app: mongoExpress
    spec:
      containers:
      - name: mongoexpress-container
        image: mongo-express
        ports:
        - containerPort: 8081 #Mongo-Express listens on 8081
        env:
        - name: ME_CONFIG_MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodburl
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username 
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password

          
                



